/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jutils_jhardware_jni_HardwareDataCollector */

#ifndef _Included_org_jutils_jhardware_jni_HardwareDataCollector
#define _Included_org_jutils_jhardware_jni_HardwareDataCollector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jutils_jhardware_jni_HardwareDataCollector
 * Method:    getGeneralData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jutils_jhardware_jni_HardwareDataCollector_getGeneralData
  (JNIEnv *, jobject);

/*
 * Class:     org_jutils_jhardware_jni_HardwareDataCollector
 * Method:    getProcessorData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jutils_jhardware_jni_HardwareDataCollector_getProcessorData
  (JNIEnv *, jobject);

/*
 * Class:     org_jutils_jhardware_jni_HardwareDataCollector
 * Method:    getMotherBoardData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jutils_jhardware_jni_HardwareDataCollector_getMotherBoardData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
